import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eco.life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-extrabold text-green-500">Eco.life</h1>
    </div>
  );
}
